web/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  scope path: :api, format: :json do
    # POST /api/products and GET /api/products/count
    resources :products, only: :create do
      collection do
        get :count
      end
    end
    namespace :webhooks do
      post "/app_uninstalled", to: "app_uninstalled#receive"
      post "/customers_data_request", to: "customers_data_request#receive"
      post "/customers_redact", to: "customers_redact#receive"
      post "/shop_redact", to: "shop_redact#receive"
    end
  end

  mount ShopifyApp::Engine, at: "/api"
  get "/api", to: redirect(path: "/") # Needed because our engine root is /api but that breaks frontend routing

  # If you are adding routes outside of the /api path, remember to also add a proxy rule for
  # them in web/frontend/vite.config.js

  get "/authenticated_file", to: "foo#authenticated_file"
  get "/unauthenticated_file", to: "foo#unauthenticated_file"

  # Any other routes will just render the react app
  match "*path" => "home#index", via: [:get, :post]
end

web/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

web/app/models/shop.rb
# frozen_string_literal: true

class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorageWithScopes

  def api_version
    ShopifyApp.configuration.api_version
  end
end

web/app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  include ShopifyApp::UserSessionStorageWithScopes

  def api_version
    ShopifyApp.configuration.api_version
  end
end

web/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

web/app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::EnsureHasSession
end

web/app/controllers/foo_controller.rb
class FooController < AuthenticatedController
  skip_around_action :activate_shopify_session, only: :unauthenticated_file

  def authenticated_file
    send_data 'foo,bar', filename: 'del.csv'
  end

  def unauthenticated_file
    send_data 'foo,bar', filename: 'del.csv'
  end
end

web/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::EnsureInstalled
  include ShopifyApp::ShopAccessScopesVerification

  DEV_INDEX_PATH = Rails.root.join("frontend")
  PROD_INDEX_PATH = Rails.public_path.join("dist")

  def index
    # removed to render index.html.erb
  end
end

web/app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < AuthenticatedController
  # GET /api/products/count
  def count
    product_count = ShopifyAPI::Product.count.body
    ShopifyAPI::Logger.info("Retrieved product count: #{product_count["count"]}")
    render(json: product_count)
  end

  # POST /api/products
  def create
    ProductCreator.call(count: 5, session: current_shopify_session, id_token: shopify_id_token)
    render(json: { success: true, error: nil })
  rescue StandardError => e
    logger.error("Failed to create products: #{e.message}")
    render(json: { success: false, error: e.message }, status: e.try(:code) || :internal_server_error)
  end
end

web/app/controllers/webhooks/app_uninstalled_controller.rb
# frozen_string_literal: true

module Webhooks
  class AppUninstalledController < ApplicationController
    include ShopifyApp::WebhookVerification

    def receive
      webhook_request = ShopifyAPI::Webhooks::Request.new(raw_body: request.raw_post, headers: request.headers.to_h)
      AppUninstalledJob.perform_later(shop_domain: webhook_request.shop, webhook: webhook_request.parsed_body)
      head(:no_content)
    end
  end
end

web/app/controllers/webhooks/customer_data_request_controller.rb
# frozen_string_literal: true

module Webhooks
  class CustomerDataRequestController < ApplicationController
    include ShopifyApp::WebhookVerification

    def receive
      webhook_request = ShopifyAPI::Webhooks::Request.new(raw_body: request.raw_post, headers: request.headers.to_h)
      CustomerDataRequestJob.perform_later(shop_domain: webhook_request.shop, webhook: webhook_request.parsed_body)
      head(:no_content)
    end
  end
end

web/app/controllers/webhooks/customer_redact_controller.rb
# frozen_string_literal: true

module Webhooks
  class CustomerRedactController < ApplicationController
    include ShopifyApp::WebhookVerification

    def receive
      webhook_request = ShopifyAPI::Webhooks::Request.new(raw_body: request.raw_post, headers: request.headers.to_h)
      CustomerRedactJob.perform_later(shop_domain: webhook_request.shop, webhook: webhook_request.parsed_body)
      head(:no_content)
    end
  end
end

web/app/controllers/webhooks/shop_redact_controller.rb
# frozen_string_literal: true

module Webhooks
  class ShopRedactController < ApplicationController
    include ShopifyApp::WebhookVerification

    def receive
      webhook_request = ShopifyAPI::Webhooks::Request.new(raw_body: request.raw_post, headers: request.headers.to_h)
      ShopRedactJob.perform_later(shop_domain: webhook_request.shop, webhook: webhook_request.parsed_body)
      head(:no_content)
    end
  end
end

web/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

web/app/views/home/index.html.erb
<%= link_to 'Authenticated File', authenticated_file_path %>
<%= link_to 'Unauthenticated File', unauthenticated_file_path %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyAppTemplateRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web/app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% elsif ShopifyApp.use_importmap? %>
      <%= javascript_importmap_tags %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'https://cdn.shopify.com/shopifycloud/app-bridge.js', data: {
      'api-key': ShopifyApp.configuration.api_key,
    } %>
  </head>

  <body>
    <ui-title-bar title="Shopify App"></ui-title-bar>

    <%= yield %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>